import { randomUUID } from "crypto";
import { hashPassword } from "@/lib/auth/password";
import {
  DEFAULT_PAYMENT_GATEWAYS,
  DEFAULT_SITE_CMS,
} from "@/lib/certificate-settings";
import type { AdminDatabase } from "./types";

const now = () => new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();
const demoPasswordHash = hashPassword("password123");

function id() {
  return randomUUID();
}

export function createSeedDatabase(): AdminDatabase {
  const catTech = id();
  const catWeb = id();
  const catWebFront = id();
  const catWebBack = id();
  const catData = id();
  const catDataMl = id();
  const catDesign = id();
  const catDesignUi = id();
  const catMkt = id();
  const inst1 = id();
  const inst2 = id();
  const inst3 = id();
  const userArjun = "demo-student";
  const userKavita = id();
  const userAdmin = id();
  const userEmma = id();
  const course1 = id();
  const course2 = id();
  const course3 = id();
  const sec1 = id();
  const sec2 = id();
  const course2Sec = id();
  const quiz1 = id();
  const order1 = id();
  const order2 = id();
  const pay1 = id();
  const pay2 = id();
  const lessonQuiz1 = id();
  const lessonQuiz1Lesson = id();
  const lq1o1 = id();
  const lq1o2 = id();
  const lq1o3 = id();
  const lq1o4 = id();
  const q1o1 = id();
  const q1o2 = id();
  const q1o3 = id();
  const q1o4 = id();
  const q2o1 = id();
  const q2o2 = id();
  const q3o1 = id();
  const q3o2 = id();
  const q3o3 = id();
  const q3o4 = id();
  const assgn1 = id();
  const assgn2 = id();
  const sub1 = id();
  const sub2 = id();
  const attempt1 = id();
  const attempt2 = id();
  const attempt3 = id();
  const cert1 = id();
  const subPlan1 = id();
  const subPlan2 = id();

  return {
    settings: {
      siteName: "Madinano",
      siteEmail: "support@madinano.com",
      sitePhone: "+91 12345 67890",
      currency: "INR",
      timezone: "Asia/Kolkata",
      maintenanceMode: false,
      allowRegistration: true,
      certificate: {
        organizationName: "Madinano",
        organizationSubtitle: "Global Pvt. Ltd.",
        director: { name: "Dr. A. K. Sharma", title: "Director", signatureImage: "" },
        registrar: { name: "R. Mehta", title: "Registrar", signatureImage: "" },
      },
      paymentGateways: {
        razorpay: { ...DEFAULT_PAYMENT_GATEWAYS.razorpay },
        cashfree: { ...DEFAULT_PAYMENT_GATEWAYS.cashfree },
        primary: DEFAULT_PAYMENT_GATEWAYS.primary,
      },
      cms: {
        ...DEFAULT_SITE_CMS,
        home: { ...DEFAULT_SITE_CMS.home },
      },
    },
    categories: [
      { id: catTech, name: "Academic Programs", slug: "academic-programs", parentId: null, level: 1, order: 1, courseCount: 0, status: "active", description: "Academic and competitive exam programs", createdAt: daysAgo(90), updatedAt: now() },
      { id: catWeb, name: "Civil Services", slug: "civil-services", parentId: catTech, level: 2, order: 1, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catWebFront, name: "UPSC Foundation", slug: "upsc-foundation", parentId: catWeb, level: 3, order: 1, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catWebBack, name: "State PCS", slug: "state-pcs", parentId: catWeb, level: 3, order: 2, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catData, name: "Research & Writing", slug: "research-writing", parentId: catTech, level: 2, order: 2, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catDataMl, name: "Research Methods", slug: "research-methods", parentId: catData, level: 3, order: 1, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catDesign, name: "Languages", slug: "languages", parentId: null, level: 1, order: 2, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catDesignUi, name: "Hindi & Urdu", slug: "hindi-urdu", parentId: catDesign, level: 2, order: 1, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
      { id: catMkt, name: "Teacher Education", slug: "teacher-education", parentId: null, level: 1, order: 3, courseCount: 0, status: "active", createdAt: daysAgo(90), updatedAt: now() },
    ],
    instructors: [
      {
        id: inst1,
        name: "Dr. Rajesh Kumar",
        email: "rajesh.kumar@madinano.com",
        expertise: "Civil Services",
        title: "UPSC Mentor",
        slug: "dr-rajesh-kumar",
        bio: "Former civil services trainer with 15+ years guiding UPSC and state PCS aspirants.",
        country: "India",
        city: "New Delhi",
        avatarUrl: "/images/instructor-1.jpg",
        courses: 2,
        students: 2,
        rating: 4.9,
        status: "active",
        createdAt: daysAgo(120),
        updatedAt: now(),
      },
      {
        id: inst2,
        name: "Prof. Meera Iyer",
        email: "meera.iyer@madinano.com",
        expertise: "Research Methods",
        title: "Research Director",
        slug: "prof-meera-iyer",
        bio: "Research scholar and academic mentor specialising in methodology and scholarly writing.",
        country: "India",
        city: "Pune",
        avatarUrl: "/images/instructor-2.jpg",
        courses: 1,
        students: 1,
        rating: 4.8,
        status: "active",
        createdAt: daysAgo(100),
        updatedAt: now(),
      },
      {
        id: inst3,
        name: "Dr. Sana Rahman",
        email: "emma@madinano.com",
        expertise: "Education & Hindi",
        title: "Senior Faculty",
        slug: "dr-sana-rahman",
        bio: "Educator focused on NEP 2020 pedagogy, Hindi literature, and teacher development.",
        country: "India",
        city: "Lucknow",
        avatarUrl: "/images/instructor-4.jpg",
        courses: 0,
        students: 0,
        rating: 4.7,
        status: "active",
        userId: userEmma,
        createdAt: daysAgo(80),
        updatedAt: now(),
      },
    ],
    users: [
      { id: userArjun, name: "Arjun Mehta", email: "arjun.mehta@email.com", role: "student", status: "active", phone: "+91 98102 34567", country: "India", city: "New Delhi", passwordHash: demoPasswordHash, createdAt: daysAgo(2), updatedAt: now() },
      { id: userKavita, name: "Kavita Singh", email: "kavita.singh@email.com", role: "student", status: "active", phone: "+91 98290 11223", country: "India", city: "Jaipur", passwordHash: demoPasswordHash, createdAt: daysAgo(5), updatedAt: now() },
      { id: userAdmin, name: "Admin User", email: "admin@madinano.com", role: "admin", status: "active", country: "India", city: "Delhi", passwordHash: demoPasswordHash, createdAt: daysAgo(365), updatedAt: now() },
      { id: userEmma, name: "Dr. Sana Rahman", email: "emma@madinano.com", role: "instructor", status: "active", country: "India", city: "Lucknow", instructorId: inst3, passwordHash: demoPasswordHash, createdAt: daysAgo(30), updatedAt: now() },
    ],
    enrollments: [
      { id: id(), userId: userArjun, courseId: course1, courseTitle: "UPSC Civil Services Foundation", progress: 65, status: "active", enrolledAt: daysAgo(10), createdAt: daysAgo(10), updatedAt: now() },
      { id: id(), userId: userArjun, courseId: course2, courseTitle: "Research Methodology & Academic Writing", progress: 40, status: "active", enrolledAt: daysAgo(20), createdAt: daysAgo(20), updatedAt: now() },
      { id: id(), userId: userKavita, courseId: course1, courseTitle: "UPSC Civil Services Foundation", progress: 25, status: "active", enrolledAt: daysAgo(3), createdAt: daysAgo(3), updatedAt: now() },
      { id: id(), userId: userKavita, courseId: course2, courseTitle: "Research Methodology & Academic Writing", progress: 85, status: "active", enrolledAt: daysAgo(15), createdAt: daysAgo(15), updatedAt: now() },
    ],
    courses: [
      {
        id: course1,
        title: "UPSC Civil Services Foundation",
        shortDescription: "GS, CSAT, essay writing & current affairs for UPSC aspirants",
        description: "A structured foundation program covering Indian polity, history, geography, economy, CSAT, essay writing, and daily current affairs for UPSC and state civil services.",
        categoryId: catWebFront,
        mainCategoryId: catTech,
        subCategoryId: catWeb,
        subSubCategoryId: catWebFront,
        instructorId: inst1,
        originalPrice: 1999,
        sellingPrice: 499,
        price: 499,
        enrollments: 2,
        rating: 4.8,
        status: "published",
        level: "intermediate",
        mode: "hybrid",
        duration: "16 weeks",
        language: "Hindi & English",
        requirements: ["Graduation or final-year student", "Basic reading habit"],
        outcomes: ["Build a strong GS & CSAT base", "Write structured answers and essays", "Follow a daily current-affairs routine"],
        curriculum: [
          { id: sec1, title: "Indian Polity & Constitution", description: "Governance fundamentals", order: 1 },
          { id: sec2, title: "Answer Writing & Essay", description: "Exam skills", order: 2 },
        ],
        finalExamQuizId: quiz1,
        thumbnailUrl: "/images/course-business.jpg",
        createdAt: daysAgo(60),
        updatedAt: now(),
      },
      {
        id: course2,
        title: "Research Methodology & Academic Writing",
        shortDescription: "Design studies, analyse data, and publish quality research",
        description: "Learn research design, literature review, qualitative and quantitative methods, citation standards, and academic writing for journals and dissertations.",
        categoryId: catDataMl,
        mainCategoryId: catTech,
        subCategoryId: catData,
        subSubCategoryId: catDataMl,
        instructorId: inst2,
        originalPrice: 1999,
        sellingPrice: 499,
        price: 499,
        enrollments: 2,
        rating: 4.7,
        status: "published",
        level: "intermediate",
        mode: "recorded",
        duration: "10 weeks",
        language: "English",
        requirements: ["Basic familiarity with academic reading"],
        outcomes: ["Draft a research proposal", "Apply basic statistical analysis", "Prepare manuscripts for publication"],
        curriculum: [{ id: course2Sec, title: "Research Design Basics", order: 1 }],
        thumbnailUrl: "/images/course-datascience.jpg",
        createdAt: daysAgo(55),
        updatedAt: now(),
      },
      {
        id: course3,
        title: "Hindi Sahitya aur Bhasha",
        shortDescription: "Classical and modern Hindi literature with language mastery",
        description: "Explore Hindi sahitya, vyakaran, lekhan kala, and comprehension for competitive exams, teaching, and cultural literacy.",
        categoryId: catDesignUi,
        mainCategoryId: catDesign,
        subCategoryId: catDesignUi,
        instructorId: inst2,
        originalPrice: 1499,
        sellingPrice: 399,
        price: 399,
        enrollments: 0,
        rating: 4.6,
        status: "published",
        level: "beginner",
        mode: "live",
        duration: "8 weeks",
        language: "Hindi",
        requirements: [],
        outcomes: ["Read and interpret key Hindi texts", "Improve written and spoken Hindi", "Prepare for teaching and exam modules"],
        curriculum: [{ id: id(), title: "Sahitya aur Vyakaran", order: 1 }],
        thumbnailUrl: "/images/course-design.jpg",
        createdAt: daysAgo(50),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "NEP 2020 Teacher Training Program",
        shortDescription: "Pedagogy, assessment, and classroom practice under NEP 2020",
        description: "Practical teacher training on NEP 2020 frameworks, inclusive pedagogy, ICT in classrooms, and competency-based assessment.",
        categoryId: catMkt,
        mainCategoryId: catMkt,
        instructorId: inst1,
        originalPrice: 1499,
        sellingPrice: 399,
        price: 399,
        enrollments: 0,
        rating: 4.7,
        status: "published",
        level: "beginner",
        mode: "recorded",
        duration: "6 weeks",
        language: "Hindi & English",
        requirements: ["Teaching interest or B.Ed./D.El.Ed. background helpful"],
        outcomes: ["Apply NEP-aligned lesson planning", "Use formative assessment tools", "Integrate digital resources in teaching"],
        curriculum: [{ id: id(), title: "NEP Pedagogy Foundations", order: 1 }],
        thumbnailUrl: "/images/course-marketing.jpg",
        createdAt: daysAgo(45),
        updatedAt: now(),
      },
    ],
    lessons: [
      {
        id: id(),
        title: "Indian Polity Overview",
        courseId: course1,
        sectionId: sec1,
        description: "Introduction to Indian polity and constitutional framework",
        duration: "45m",
        order: 1,
        status: "published",
        lessonType: "video",
        videoProvider: "youtube",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        videoId: "dQw4w9WgXcQ",
        isPrivateVideo: false,
        createdAt: daysAgo(60),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Constitution & Governance",
        courseId: course1,
        sectionId: sec1,
        duration: "1h 20m",
        order: 2,
        status: "published",
        lessonType: "video",
        videoProvider: "youtube",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        videoId: "dQw4w9WgXcQ",
        isPrivateVideo: false,
        createdAt: daysAgo(59),
        updatedAt: now(),
      },
      {
        id: lessonQuiz1Lesson,
        title: "Polity & Constitution Quick Check",
        courseId: course1,
        sectionId: sec1,
        description: "Short quiz on polity and governance basics",
        duration: "10m",
        order: 3,
        status: "published",
        lessonType: "quiz",
        quizId: lessonQuiz1,
        createdAt: daysAgo(58),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Research Design Basics",
        courseId: course2,
        sectionId: course2Sec,
        duration: "55m",
        order: 1,
        status: "published",
        lessonType: "video",
        videoProvider: "youtube",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        videoId: "dQw4w9WgXcQ",
        createdAt: daysAgo(55),
        updatedAt: now(),
      },
    ],
    assignments: [
      {
        id: assgn1,
        title: "Essay Writing Assignment",
        courseId: course1,
        sectionId: sec1,
        description: "Write a structured essay on federalism and cooperative governance",
        instructions: "Submit a 1200-word essay with introduction, body, and conclusion. Include at least three references.",
        dueDate: daysAgo(-7),
        maxMarks: 100,
        allowLateSubmission: true,
        submissions: 1,
        status: "open",
        createdAt: daysAgo(30),
        updatedAt: now(),
      },
      {
        id: assgn2,
        title: "Research Proposal Draft",
        courseId: course2,
        sectionId: course2Sec,
        description: "Draft a research proposal on a topic of your choice",
        instructions: "Upload a PDF proposal (max 8 pages) with objectives, methodology, and timeline.",
        dueDate: daysAgo(-14),
        maxMarks: 50,
        allowLateSubmission: false,
        submissions: 1,
        status: "open",
        createdAt: daysAgo(25),
        updatedAt: now(),
      },
    ],
    assignmentSubmissions: [
      {
        id: sub1,
        assignmentId: assgn1,
        userId: userArjun,
        content: "Submitted essay on federalism, cooperative governance, and centre-state relations.",
        status: "submitted",
        submittedAt: daysAgo(2),
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
      },
      {
        id: sub2,
        assignmentId: assgn2,
        userId: userKavita,
        content: "Submitted research proposal on rural education outcomes in Rajasthan.",
        status: "graded",
        marks: 42,
        feedback: "Good analysis. Add more detail on outlier handling.",
        submittedAt: daysAgo(5),
        createdAt: daysAgo(5),
        updatedAt: daysAgo(3),
      },
    ],
    quizzes: [
      {
        id: lessonQuiz1,
        title: "Polity & Constitution Quick Check",
        description: "Short lesson quiz after polity videos",
        courseId: course1,
        courseTitle: "UPSC Civil Services Foundation",
        quizKind: "lesson_quiz",
        lessonId: lessonQuiz1Lesson,
        durationMinutes: 10,
        totalMarks: 2,
        passingMarks: 1,
        passingPercentage: 50,
        maxAttempts: 5,
        shuffleQuestions: true,
        shuffleOptions: true,
        showResultsInstantly: true,
        issueCertificateOnPass: false,
        enableProctoring: false,
        maxProctorViolations: 3,
        autoSubmitOnProctorViolation: false,
        requireFullscreen: false,
        questionItems: [
          {
            id: id(),
            text: "Which part of the Constitution deals with fundamental rights?",
            type: "mcq",
            options: [
              { id: lq1o1, text: "Part III" },
              { id: lq1o2, text: "Part IV" },
              { id: lq1o3, text: "Part II" },
              { id: lq1o4, text: "Part V" },
            ],
            correctOptionIds: [lq1o1],
            marks: 1,
            order: 1,
          },
        ],
        questions: 1,
        attempts: 1,
        status: "active",
        createdAt: daysAgo(58),
        updatedAt: now(),
      },
      {
        id: quiz1,
        title: "UPSC Foundation Final Examination",
        description: "Comprehensive exam covering polity, governance, and essay skills",
        courseId: course1,
        courseTitle: "UPSC Civil Services Foundation",
        quizKind: "final_exam",
        instructions: "Read each question carefully. You have 45 minutes. Passing score is 60%. No negative marking unless stated.",
        durationMinutes: 45,
        totalMarks: 5,
        passingMarks: 3,
        passingPercentage: 60,
        maxAttempts: 3,
        shuffleQuestions: true,
        shuffleOptions: true,
        showResultsInstantly: true,
        issueCertificateOnPass: true,
        enableProctoring: true,
        maxProctorViolations: 3,
        autoSubmitOnProctorViolation: true,
        requireFullscreen: false,
        questionItems: [
          {
            id: id(),
            text: "Which article abolished untouchability?",
            type: "mcq",
            options: [
              { id: q1o1, text: "Article 17" },
              { id: q1o2, text: "Article 14" },
              { id: q1o3, text: "Article 21" },
              { id: q1o4, text: "Article 32" },
            ],
            correctOptionIds: [q1o1],
            marks: 1,
            order: 1,
            explanation: "Article 17 abolishes untouchability and forbids its practice.",
          },
          {
            id: id(),
            text: "The President of India is elected by an electoral college.",
            type: "true_false",
            options: [
              { id: q2o1, text: "True" },
              { id: q2o2, text: "False" },
            ],
            correctOptionIds: [q2o1],
            marks: 1,
            order: 2,
          },
          {
            id: id(),
            text: "Which of the following are fundamental rights? (Select all that apply)",
            type: "multi_select",
            options: [
              { id: q3o1, text: "Right to Equality" },
              { id: q3o2, text: "Right to Freedom" },
              { id: q3o3, text: "Right against Exploitation" },
              { id: q3o4, text: "Right to Property (original)" },
            ],
            correctOptionIds: [q3o1, q3o2, q3o3],
            marks: 2,
            order: 3,
          },
        ],
        questions: 3,
        attempts: 2,
        status: "active",
        createdAt: daysAgo(40),
        updatedAt: now(),
      },
    ],
    quizAttempts: [
      {
        id: attempt1,
        quizId: quiz1,
        quizTitle: "UPSC Foundation Final Examination",
        studentId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        startedAt: daysAgo(3),
        submittedAt: daysAgo(3),
        answers: {},
        score: 4,
        totalMarks: 5,
        percentage: 80,
        passed: true,
        timeTakenSeconds: 2100,
        status: "submitted",
        certificateId: cert1,
        tabSwitchCount: 0,
        proctoringViolations: [],
        questionResults: [],
        createdAt: daysAgo(3),
        updatedAt: daysAgo(3),
      },
      {
        id: attempt2,
        quizId: quiz1,
        quizTitle: "UPSC Foundation Final Examination",
        studentId: userKavita,
        studentName: "Kavita Singh",
        studentEmail: "kavita.singh@email.com",
        startedAt: daysAgo(5),
        submittedAt: daysAgo(5),
        answers: {},
        score: 2,
        totalMarks: 5,
        percentage: 40,
        passed: false,
        timeTakenSeconds: 1800,
        status: "submitted",
        tabSwitchCount: 2,
        proctoringViolations: [
          { type: "tab_switch", at: daysAgo(5), detail: "Switched tab" },
          { type: "window_blur", at: daysAgo(5), detail: "Window lost focus" },
        ],
        questionResults: [],
        createdAt: daysAgo(5),
        updatedAt: daysAgo(5),
      },
      {
        id: attempt3,
        quizId: lessonQuiz1,
        quizTitle: "Polity & Constitution Quick Check",
        studentId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        startedAt: daysAgo(0),
        answers: {},
        score: 0,
        totalMarks: 2,
        percentage: 0,
        passed: false,
        timeTakenSeconds: 0,
        status: "in_progress",
        tabSwitchCount: 0,
        createdAt: daysAgo(0),
        updatedAt: daysAgo(0),
      },
    ],
    certificates: [
      {
        id: cert1,
        certificateNo: "NBG-CERT-2026-DEMO0001",
        studentId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        courseTitle: "UPSC Civil Services Foundation",
        quizTitle: "UPSC Foundation Final Examination",
        quizId: quiz1,
        attemptId: attempt1,
        score: 4,
        percentage: 80,
        issuedAt: daysAgo(3),
        verifyUrl: "http://localhost:3210/certificates/verify/NBG-CERT-2026-DEMO0001",
        status: "issued",
        template: "classic-maroon",
        createdAt: daysAgo(3),
        updatedAt: daysAgo(3),
      },
    ],
    liveClasses: [
      {
        id: id(),
        title: "UPSC Answer Writing Live Session",
        courseId: course1,
        sectionId: sec2,
        instructorName: "Dr. Rajesh Kumar",
        description: "Live answer writing practice with mentor feedback",
        scheduledAt: daysAgo(-1),
        duration: "1h 30m",
        enrolled: 18,
        status: "live",
        platform: "google_meet",
        meetingUrl: "https://meet.google.com/abc-defg-hij",
        createdAt: daysAgo(10),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Research Methods Workshop",
        courseId: course2,
        instructorName: "Prof. Meera Iyer",
        description: "Hands-on session on literature review and research design",
        scheduledAt: daysAgo(-3),
        duration: "2h",
        enrolled: 12,
        status: "scheduled",
        platform: "zoom",
        meetingUrl: "https://zoom.us/j/123456789",
        meetingId: "123456789",
        passcode: "ds2026",
        createdAt: daysAgo(8),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Hindi Sahitya Discussion",
        courseId: course3,
        instructorName: "Dr. Sana Rahman",
        description: "Guided discussion on modern Hindi literature",
        scheduledAt: daysAgo(5),
        duration: "1h",
        enrolled: 9,
        status: "completed",
        platform: "youtube",
        meetingUrl: "https://youtube.com/live/example",
        youtubeLiveUrl: "https://youtube.com/live/example",
        createdAt: daysAgo(20),
        updatedAt: now(),
      },
    ],
    orders: [
      {
        id: order1,
        orderNo: "ORD-2026-0001",
        userId: userKavita,
        studentName: "Kavita Singh",
        studentEmail: "kavita.singh@email.com",
        courseId: course1,
        courseTitle: "UPSC Civil Services Foundation",
        amount: 499,
        status: "completed",
        paymentId: pay1,
        createdAt: daysAgo(0),
        updatedAt: now(),
      },
      {
        id: order2,
        orderNo: "ORD-2026-0002",
        userId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        courseId: course2,
        courseTitle: "Research Methodology & Academic Writing",
        amount: 499,
        status: "completed",
        paymentId: pay2,
        createdAt: daysAgo(1),
        updatedAt: now(),
      },
    ],
    payments: [
      {
        id: pay1,
        orderId: order1,
        orderNo: "ORD-2026-0001",
        userId: userKavita,
        studentName: "Kavita Singh",
        studentEmail: "kavita.singh@email.com",
        courseId: course1,
        courseTitle: "UPSC Civil Services Foundation",
        amount: 499,
        method: "upi",
        status: "completed",
        transactionId: "TXN-2026-KAVITA001",
        createdAt: daysAgo(0),
        updatedAt: now(),
      },
      {
        id: pay2,
        orderId: order2,
        orderNo: "ORD-2026-0002",
        userId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        courseId: course2,
        courseTitle: "Research Methodology & Academic Writing",
        amount: 499,
        method: "card",
        status: "completed",
        transactionId: "TXN-2026-ARJUN001",
        createdAt: daysAgo(1),
        updatedAt: now(),
      },
    ],
    subscriptions: [
      {
        id: subPlan1,
        userId: userArjun,
        studentName: "Arjun Mehta",
        studentEmail: "arjun.mehta@email.com",
        plan: "yearly",
        amount: 4999,
        startDate: daysAgo(30),
        endDate: daysAgo(-335),
        status: "active",
        autoRenew: true,
        paymentMethod: "upi",
        transactionId: "TXN-SUB-ARJUN001",
        createdAt: daysAgo(30),
        updatedAt: now(),
      },
      {
        id: subPlan2,
        userId: userKavita,
        studentName: "Kavita Singh",
        studentEmail: "kavita.singh@email.com",
        plan: "monthly",
        amount: 499,
        startDate: daysAgo(15),
        endDate: daysAgo(-15),
        status: "active",
        autoRenew: true,
        paymentMethod: "card",
        transactionId: "TXN-SUB-KAVITA001",
        createdAt: daysAgo(15),
        updatedAt: now(),
      },
    ],
    coupons: [
      { id: id(), code: "NEWYEAR50", discount: 50, discountType: "percent", usageLimit: 1000, usedCount: 8, expiresAt: daysAgo(-30), status: "active", createdAt: daysAgo(60), updatedAt: now() },
      { id: id(), code: "FLAT200", discount: 200, discountType: "fixed", usageLimit: 500, usedCount: 5, expiresAt: daysAgo(-60), status: "active", createdAt: daysAgo(45), updatedAt: now() },
    ],
    blogs: [
      {
        id: id(),
        title: "Top 10 Learning Tips for 2026",
        slug: "top-10-learning-tips-2026",
        category: "Career",
        author: "Admin",
        excerpt: "Practical habits to learn faster and stay consistent throughout the year.",
        content: "Learning in 2026 demands focus, practice and the right tools. Start with clear goals, schedule deep-work blocks, and review weekly.",
        coverImage: "/images/course-business.jpg",
        readTime: "4 min read",
        status: "published",
        publishedAt: daysAgo(5),
        createdAt: daysAgo(5),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "How to Start UPSC Preparation in 2026",
        slug: "start-upsc-preparation-2026",
        category: "Civil Services",
        author: "Dr. Rajesh Kumar",
        excerpt: "A practical roadmap for first-time UPSC aspirants.",
        content: "Begin with NCERT basics, daily current affairs, answer writing practice, and a balanced GS–CSAT schedule.",
        coverImage: "/images/course-webdev.jpg",
        readTime: "8 min read",
        status: "published",
        publishedAt: daysAgo(10),
        createdAt: daysAgo(10),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Writing Your First Research Paper",
        slug: "writing-first-research-paper",
        category: "Research",
        author: "Prof. Meera Iyer",
        excerpt: "From question to publication — steps every researcher should follow.",
        content: "Choose a focused question, review literature thoroughly, collect evidence ethically, and revise before submission.",
        coverImage: "/images/course-datascience.jpg",
        readTime: "6 min read",
        status: "published",
        publishedAt: daysAgo(12),
        createdAt: daysAgo(12),
        updatedAt: now(),
      },
    ],
    events: [
      { id: id(), title: "Madinano Research & Education Summit 2026", date: daysAgo(-30), location: "New Delhi, India", attendees: 120, status: "upcoming", createdAt: daysAgo(20), updatedAt: now() },
    ],
    testimonials: [
      {
        id: id(),
        name: "Vikram Joshi",
        role: "UPSC Aspirant",
        quote: "The foundation course gave me structure for GS and answer writing. Mentors reviewed my essays every week.",
        rating: 5,
        avatarUrl: "/images/instructor-1.jpg",
        status: "published",
        createdAt: daysAgo(15),
        updatedAt: now(),
      },
      {
        id: id(),
        name: "Ananya Reddy",
        role: "Research Scholar",
        quote: "Research Methodology helped me finalize my dissertation proposal and understand publication standards.",
        rating: 5,
        avatarUrl: "/images/instructor-2.jpg",
        status: "published",
        createdAt: daysAgo(20),
        updatedAt: now(),
      },
      {
        id: id(),
        name: "Imran Khan",
        role: "School Teacher",
        quote: "The NEP teacher training modules were practical and immediately useful in my classroom.",
        rating: 5,
        avatarUrl: "/images/instructor-3.jpg",
        status: "published",
        createdAt: daysAgo(8),
        updatedAt: now(),
      },
    ],
    gallery: [
      { id: id(), title: "Graduation Ceremony 2025", imageUrl: "/images/course-webdev.jpg", category: "Events", status: "published", createdAt: daysAgo(30), updatedAt: now() },
    ],
    cmsPages: [
      {
        id: id(),
        title: "About Us",
        slug: "about",
        status: "published",
        excerpt: "Empowering learners worldwide through research-led education.",
        seoTitle: "About Us | Madinano",
        content: "Madinano is a next-generation online learning platform dedicated to helping students, professionals, and organizations unlock their true potential.\n\nOur mission is to empower individuals through accessible, affordable, and high-quality education.\n\nWhy choose us:\n- Expert instructors\n- Flexible learning\n- Practical high-quality content\n- Affordable education\n- Lifetime access\n- Global community",
        createdAt: daysAgo(100),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Privacy Policy",
        slug: "privacy-policy",
        status: "published",
        excerpt: "How we collect, use, and protect your information.",
        content: "1. Information we collect\nWe collect account details, billing address, course progress, exam attempts, and support messages.\n\n2. How we use your data\nTo create accounts, process enrollments/payments, issue certificates, and provide support.\n\n3. Sharing\nWe do not sell personal data. Payment processors may receive limited data to complete transactions.\n\n4. Your choices\nUpdate your profile from the dashboard or contact support.\n\nLast updated: July 2026",
        createdAt: daysAgo(100),
        updatedAt: now(),
      },
      {
        id: id(),
        title: "Terms of Use",
        slug: "terms",
        status: "published",
        excerpt: "Rules for using courses, exams, and platform services.",
        content: "1. Accounts\nProvide accurate information and keep credentials secure.\n\n2. Course purchases\nAccess is personal. Do not share accounts or redistribute materials.\n\n3. Certificates & exams\nIssued only after requirements are met. Proctoring rules may apply.\n\n4. Refunds\nReviewed case by case — contact support with your order number.\n\nLast updated: July 2026",
        createdAt: daysAgo(100),
        updatedAt: now(),
      },
    ],
    faq: [
      { id: id(), question: "Is Madinano beginner friendly?", answer: "Yes — every track starts from zero with step-by-step lessons and mentor support.", category: "General", status: "published", order: 1, createdAt: daysAgo(50), updatedAt: now() },
      { id: id(), question: "Do I get a certificate?", answer: "Yes. Every graduate who passes the final exam receives a verifiable digital certificate.", category: "General", status: "published", order: 2, createdAt: daysAgo(50), updatedAt: now() },
      { id: id(), question: "Can I learn at my own pace?", answer: "Absolutely. Recorded courses are self-paced, and live classes are optional for hybrid tracks.", category: "Learning", status: "published", order: 3, createdAt: daysAgo(50), updatedAt: now() },
      { id: id(), question: "What if I fall behind in a cohort?", answer: "All live sessions are recorded and every cohort has a self-paced companion track.", category: "Learning", status: "published", order: 4, createdAt: daysAgo(50), updatedAt: now() },
      { id: id(), question: "How do payments and refunds work?", answer: "You can pay via UPI, card or net banking. Refunds follow our 7-day policy for unused courses.", category: "Billing", status: "published", order: 5, createdAt: daysAgo(50), updatedAt: now() },
    ],
    roles: [
      { id: id(), name: "Super Admin", permissions: ["*"], userCount: 1, createdAt: daysAgo(365), updatedAt: now() },
      { id: id(), name: "Instructor", permissions: ["courses:read", "courses:write", "students:read"], userCount: 3, createdAt: daysAgo(365), updatedAt: now() },
      { id: id(), name: "Student", permissions: ["courses:read", "profile:write"], userCount: 2, createdAt: daysAgo(365), updatedAt: now() },
    ],
    systemLogs: [
      { id: id(), action: "User login", user: "admin@madinano.com", module: "auth", ip: "192.168.1.1", level: "info", createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), action: "Course published", user: "rajesh.kumar@madinano.com", module: "courses", ip: "192.168.1.2", level: "info", createdAt: daysAgo(1), updatedAt: now() },
    ],
    activities: [
      { id: id(), message: "New student Arjun Mehta registered", type: "user", color: "bg-emerald-500", audience: "admin", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), message: "Course 'Research Methodology & Academic Writing' published", type: "course", color: "bg-sky-500", audience: "all", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), message: "Payment of ₹499 received from Kavita Singh", type: "payment", color: "bg-amber-500", audience: "admin", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), message: "New instructor Dr. Sana Rahman joined", type: "instructor", color: "bg-fuchsia-500", audience: "admin", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), message: "Live class 'UPSC Answer Writing' started", type: "live", color: "bg-rose-500", audience: "all", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
      { id: id(), message: "Your enrollment in UPSC Civil Services Foundation is active", type: "enrollment", color: "bg-emerald-500", audience: "student", userId: userArjun, href: "/dashboard", readBy: [], createdAt: daysAgo(0), updatedAt: now() },
    ],
    newsletterSubscribers: [],
    emailOutbox: [],
  };
}
